#!/bin/bash

mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" mysql 

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" << EOF
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE} CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS ${MYSQL_USER}@localhost IDENTIFIED BY "${MYSQL_PASSWORD}";
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON ${MYSQL_DATABASE}.* TO "${MYSQL_USER}"@'%' IDENTIFIED BY "${MYSQL_PASSWORD}"; 
FLUSH PRIVILEGES;
exit
EOF